spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: racher
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

weather-api:
  url: http://api.weatherapi.com/v1/current.json
  token: ${TOKEN}
  limit: 1000000
